# 考虑到 mysql, redis, Nginx 可能被多个服务共用，所以拆分到 docker-compose-common.yml 中
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data
      - /data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
