# 考虑到 mysql, redis, Nginx 可能被多个服务共用，所以拆分到 docker-compose-common.yml 中

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      # 这里使用绝对路径是为了方便理解项目结构， docker-compose-common.yml 位于 /data 目录下
      # 一般来说为了通用应该使用相对路径，以便可以直接迁移到其它服务器
      - /data/redis/data:/data
      - /data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/logs:/var/log/nginx
      - /data/frontend/dist:/data/frontend/dist:ro
    environment:
      - TZ=Asia/Shanghai