"""empty message

Revision ID: 20202a7cad0a
Revises: 3ce6a7e1441d
Create Date: 2026-01-13 23:14:29.698753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20202a7cad0a'
down_revision = '3ce6a7e1441d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###
