"""empty message

Revision ID: 3ce6a7e1441d
Revises: 579a342bb88c
Create Date: 2026-01-13 23:04:11.183884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ce6a7e1441d'
down_revision = '579a342bb88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###
