"""empty message

Revision ID: 42a581ab15b0
Revises: 20202a7cad0a
Create Date: 2026-01-14 14:45:26.460807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a581ab15b0'
down_revision = '20202a7cad0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否展示'))
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=255),
               comment='url,前端使用',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment='导航栏名称',
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               comment='父导航栏ID',
               existing_comment='父菜单ID',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_menu_is_visible'), ['is_visible'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_is_visible'))
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               comment='父菜单ID',
               existing_comment='父导航栏ID',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='导航栏名称',
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='url,前端使用',
               existing_nullable=False)
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
