"""empty message

Revision ID: 579a342bb88c
Revises: 797d037705b0
Create Date: 2026-01-13 22:55:46.774454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '579a342bb88c'
down_revision = '797d037705b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_comment='父菜单ID')

    # ### end Alembic commands ###
