"""empty message

Revision ID: 5d1bca12fab8
Revises: 8aa8c270e402
Create Date: 2026-01-01 13:48:56.078170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d1bca12fab8'
down_revision = '8aa8c270e402'
branch_labels = None
depends_on = None


def upgrade():
    # 之前 isbn 找不到允许为空，后面找到了设置不允许为空
    op.execute('''
               UPDATE book
               SET isbn = CONCAT('TEMP_', id)
               WHERE isbn IS NULL
               ''')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
                              existing_type=mysql.VARCHAR(length=128),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
                              existing_type=mysql.VARCHAR(length=128),
                              nullable=True)

    # ### end Alembic commands ###
