"""empty message

Revision ID: 8aa8c270e402
Revises: a18489680f73
Create Date: 2025-12-31 15:31:25.927157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8aa8c270e402'
down_revision = 'a18489680f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_index(batch_op.f('isbn'))
        batch_op.create_index(batch_op.f('ix_book_isbn'), ['isbn'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_isbn'))
        batch_op.create_index(batch_op.f('isbn'), ['isbn'], unique=True)
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
