"""empty message

Revision ID: a18489680f73
Revises: 07f1446c9aab
Create Date: 2025-12-30 22:52:24.895488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a18489680f73'
down_revision = '07f1446c9aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=20, scale=2),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
