"""empty message

Revision ID: a4e216753f2e
Revises: ca683e3ab8df
Create Date: 2026-01-13 16:21:59.831577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4e216753f2e'
down_revision = 'ca683e3ab8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')

    # ### end Alembic commands ###
