"""empty message

Revision ID: cf030abf5052
Revises: 42a581ab15b0
Create Date: 2026-01-18 23:41:26.953638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf030abf5052'
down_revision = '42a581ab15b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_name'))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
