"""empty message

Revision ID: df8980f12680
Revises: cf030abf5052
Create Date: 2026-01-19 08:29:40.335710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8980f12680'
down_revision = 'cf030abf5052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False, comment='展示顺序'))
        batch_op.create_index(batch_op.f('ix_menu_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_parent_id'))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
